# Generated by Django 4.2.17 on 2024-12-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_path', models.ImageField(upload_to='movie_images/')),
                ('description', models.TextField()),
                ('description2', models.TextField()),
            ],
        ),
    ]
