# Generated by Django 4.2.17 on 2024-12-07 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='overview',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image_path',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.URLField(default='https://via.placeholder.com/500'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='movie_management.movie')),
            ],
        ),
    ]
