# Generated by Django 4.2.17 on 2024-12-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0002_rename_description_movie_overview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='overview',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_path',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='like',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='movie_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='description2',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='image_path',
            field=models.ImageField(default='https://via.placeholder.com/500', upload_to='movie_images/'),
            preserve_default=False,
        ),
    ]
