# Generated by Django 4.2.17 on 2024-12-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0003_rename_overview_movie_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='like',
            name='movie_id',
            field=models.IntegerField(unique=True),
        ),
    ]
